//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trend
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DefBroker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefBroker()
        {
            this.LedLeads = new HashSet<LedLead>();
        }

        public int ID { get; set; }
        [Required]
        public string BrokerName { get; set; }
        public string WebSite { get; set; }
        [Required]
        public string Email { get; set; }
        public string Address { get; set; }
        public string Industry { get; set; }
        [Required]
        public string FK_CreatorID { get; set; }
        [Required]
        public System.DateTime CreationDate { get; set; }
        [Required]
        public System.DateTime LastModifiedDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedLead> LedLeads { get; set; }
    }
}
