//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trend
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefContact()
        {
            this.LedLeads = new HashSet<LedLead>();
            this.LedLeadClientContacts = new HashSet<LedLeadClientContact>();
        }
    
        public int ID { get; set; }
        public int FK_DefContactReferenceTypeID { get; set; }
        public int FK_ReferenceID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Position { get; set; }
        public string Telephone { get; set; }
        public string Telephone1 { get; set; }
        public string Mobile { get; set; }
        public string Mobile1 { get; set; }
        public string Fax { get; set; }
        public string FK_CreatorID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual DefContactReferenceType DefContactReferenceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedLead> LedLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedLeadClientContact> LedLeadClientContacts { get; set; }
    }
}
