//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trend
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedLead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LedLead()
        {
            this.LedLeadClientContacts = new HashSet<LedLeadClientContact>();
            this.LedLeadFroms = new HashSet<LedLeadFrom>();
        }
    
        public int ID { get; set; }
        public int FK_DefCompanyID { get; set; }
        public int LeadSerial { get; set; }
        public string LeadName { get; set; }
        public System.DateTime LeadDate { get; set; }
        public Nullable<decimal> NewOfficeSize { get; set; }
        public string NewOfficeAddress { get; set; }
        public Nullable<decimal> ExpectedBudget { get; set; }
        public int FK_DefClientID { get; set; }
        public Nullable<int> FK_DefBrokerID { get; set; }
        public Nullable<int> FK_BrokerDefContactID { get; set; }
        public Nullable<int> FK_DefModuleStatusID { get; set; }
        public Nullable<int> FK_LedLeadSourceID { get; set; }
        public Nullable<int> FK_AssignedByHREmployeeID { get; set; }
        public Nullable<int> FK_AssignedToHREmployeeID { get; set; }
        public Nullable<System.DateTime> LeadAssignedDate { get; set; }
        public string Notes { get; set; }
        public string FK_CreatorID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual DefBroker DefBroker { get; set; }
        public virtual DefClient DefClient { get; set; }
        public virtual DefCompany DefCompany { get; set; }
        public virtual DefContact DefContact { get; set; }
        public virtual DefModuleStatu DefModuleStatu { get; set; }
        public virtual HREmployee HREmployee { get; set; }
        public virtual HREmployee HREmployee1 { get; set; }
        public virtual LedLeadSource LedLeadSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedLeadClientContact> LedLeadClientContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedLeadFrom> LedLeadFroms { get; set; }
    }
}
