//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrendEntities : DbContext
    {
        public TrendEntities()
            : base("name=TrendEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DefBroker> DefBrokers { get; set; }
        public virtual DbSet<DefClient> DefClients { get; set; }
        public virtual DbSet<DefCompany> DefCompanies { get; set; }
        public virtual DbSet<DefContact> DefContacts { get; set; }
        public virtual DbSet<DefContactReferenceType> DefContactReferenceTypes { get; set; }
        public virtual DbSet<DefLandlord> DefLandlords { get; set; }
        public virtual DbSet<DefModuleStatu> DefModuleStatus { get; set; }
        public virtual DbSet<HREmployee> HREmployees { get; set; }
        public virtual DbSet<LedLead> LedLeads { get; set; }
        public virtual DbSet<LedLeadClientContact> LedLeadClientContacts { get; set; }
        public virtual DbSet<LedLeadFrom> LedLeadFroms { get; set; }
        public virtual DbSet<LedLeadSource> LedLeadSources { get; set; }
        public virtual DbSet<SecModule> SecModules { get; set; }
    }
}
